### ISSUE TITLE
No plugin found named "seo"

### ISSUE THREAD

**Issue by adamwong246** [lookback/meteor-seo#11]
```
Router.plugin 'seo',
  defaults:
    title: "fooo"
    description: 'foobar'
```

```
W20151008-11:49:55.955(-7)? (STDERR) Error: No plugin found named "seo"
W20151008-11:49:55.955(-7)? (STDERR)     at Function.Router.plugin (packages/iron:router/lib/router.js:394:1)
W20151008-11:49:55.955(-7)? (STDERR)     at both/routes.coffee:8:8
W20151008-11:49:55.955(-7)? (STDERR)     at both/routes.coffee:1:1
W20151008-11:49:55.955(-7)? (STDERR)     at /Users/adam/Programming/chroma/chroma-fund/.meteor/local/build/programs/server/boot.js:222:10
W20151008-11:49:55.955(-7)? (STDERR)     at Array.forEach (native)
W20151008-11:49:55.955(-7)? (STDERR)     at Function._.each._.forEach (/Users/adam/.meteor/packages/meteor-tool/.1.1.4.vg08ae++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151008-11:49:55.956(-7)? (STDERR)     at /Users/adam/Programming/chroma/chroma-fund/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by johanbrook** [comment]
@adamwong246 It's working in the test app. Are you sure you run that code on the client?

**Comment by Ilshidur** [comment]
I figured out how to fix this problem. Just wrap your plugin config code in a "Meteor.isClient" condition :
```javascript
if (Meteor.isClient) {
    Router.plugin('seo', {
        // CONFIG HERE ...
    });
}
```

**Comment by AndyNormore** [comment]
Can confirm Ilshidur's answer, you MUST wrap this in Meteor.isClient

PLEASE update your GitHub docs! This was a frustrating plugin to setup - but it works gooood :)
